services:
  db:
    image: postgres:16-alpine
    container_name: m2_db
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    entrypoint: ["/docker-entrypoint-secrets.sh"]
    command: ["postgres"]
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker-entrypoint-secrets.sh:/docker-entrypoint-secrets.sh:ro
    networks:
      - backend
    # Pas de healthcheck au départ (à ajouter)

  backend:
    build:
      context: ./backend
    container_name: m2_backend
    environment:
      PORT: ${API_PORT}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_db
      - postgres_password
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend
    # Pas de healthcheck au départ (à ajouter)

  frontend:
    build:
      context: ./frontend
    container_name: m2_frontend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - frontend
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: m2_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - frontend
      - backend

networks:
  backend:
    name: m2_backend_net
  frontend:
    name: m2_frontend_net

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_password:
    file: ./secrets/postgres_password.txt

volumes:
  pg_data:
